import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');const path=resolve('dist','.'+(url.pathname==='/'?'/index.html':url.pathname));if(!path.startsWith(resolve('dist')+'\\'))throw Error();const data=await readFile(path);res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':path.endsWith('.webmanifest')?'application/manifest+json':path.endsWith('.png')?'image/png':'text/html');res.end(data);}catch{res.statusCode=404;res.end();}}).listen(4174);
await mkdir('screenshots',{recursive:true});let browser;const results=[];
try{browser=await chromium.launch();const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();const failures=[];page.on('pageerror',e=>failures.push(e.message));const click=async a=>page.locator(`[data-action="${a}"]`).first().click();const visible=async text=>assert(await page.getByText(text,{exact:false}).first().isVisible(),text);const shot=async name=>page.screenshot({path:`screenshots/${name}.png`,fullPage:true});
await page.goto('http://localhost:4174');await shot('01-klub-390');await click('login');await shot('02-velkommen-390');await click('verify');await click('details');await page.locator('[name=email]').fill('anders.demo@example.test');await page.locator('form button').click();await page.locator('[name=pin]').fill('9999');await page.locator('form button').click();await visible('Forkert demokode');await page.locator('[name=pin]').fill('1234');await page.locator('[name=face]').check();await page.locator('form button').click();await shot('07-medlemskab-390');await click('profile');await visible('anders.demo@example.test');await click('home');await click('request');await shot('08-anmodning-390');await click('unlock');await click('face-error');await visible('lykkedes ikke');await click('pin');await page.locator('[name=pin]').fill('0000');await page.locator('form button').click();await visible('Forkert demokode');await page.locator('[name=pin]').fill('1234');await page.locator('form button').click();await shot('09b-swipe-390');
const box=await page.locator('#handle').boundingBox();await page.mouse.move(box.x+26,box.y+26);await page.mouse.down();await page.mouse.move(box.x+70,box.y+26,{steps:6});await page.mouse.up();assert(await page.locator('#swipe').isVisible());await page.waitForTimeout(250);const track=await page.locator('#swipe').boundingBox();await page.mouse.move(box.x+26,box.y+26);await page.mouse.down();await page.mouse.move(track.x+track.width-28,box.y+26,{steps:15});await page.mouse.up();await visible('Du er nu');await shot('10-succes-390');await click('logged');await visible('Velkommen, Anders');await click('logout');await click('login');await click('unlock');assert(await page.locator('#swipe').count()===0);await click('cancel');await click('login');await click('unlock');await click('face');await page.goBack();assert(await page.locator('#swipe').count()===0);await page.reload();await click('login');await visible('Anmoder om login');await click('cancel');results.push('Ny bruger, ændrede profildata, MitID-annullering, forkert/korrekt PIN, Face ID-fejl, kort og fuldt museswipe, succes, logout, gentaget login, browser-tilbage og genindlæsning: bestået.');
await page.locator('summary').filter({hasText:'Demo'}).click();await click('reset');await click('login');await click('existing');await click('unlock');await click('face');await click('approve');await visible('Du er nu');results.push('Eksisterende bruger uden onboarding og tilgængelig godkendelsesknap efter oplåsning: bestået.');
await page.locator('summary').filter({hasText:'Demo'}).click();await click('new');await click('verify');await click('details');await page.locator('form button').click();await page.locator('[name=pin]').fill('1234');await page.locator('form button').click();await click('request');await click('unlock');await visible('Face ID blev sprunget over');await click('pin');await page.locator('[name=pin]').fill('1234');await page.locator('form button').click();await page.locator('#handle').focus();await page.keyboard.press('Enter');await visible('Du er nu');results.push('Face ID fravalgt → naturlig PIN-vej; tastaturgodkendelse: bestået.');
for(const viewport of [{width:360,height:640},{width:390,height:844},{width:1440,height:900}]){await page.setViewportSize(viewport);await page.locator('summary').filter({hasText:'Demo'}).click();await click('new');await shot(`02-velkommen-${viewport.width}x${viewport.height}`);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await click('verify');await click('details');await shot(`04-oplysninger-${viewport.width}x${viewport.height}`);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('summary').filter({hasText:'Demo'}).click();await click('demo-existing');await visible('Forbundne tjenester');await click('link-id');await visible('Forbundet som');}results.push('360×640, 390×844 og 1440×900: screenshots og kontrol for vandret overflow bestået.');
await page.evaluate(async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(r=>navigator.serviceWorker.addEventListener('controllerchange',r,{once:true}));});await context.setOffline(true);await page.reload();await click('login');await click('unlock');await click('face');await click('approve');await visible('Du er nu');await context.setOffline(false);results.push('Webbuild genindlæst og gennemført offline efter aktiveret service worker/cache: bestået.');
const localContext=await browser.newContext({offline:true});const local=await localContext.newPage();let external=0;local.on('request',r=>{if(/^https?:/.test(r.url()))external++;});await local.goto(pathToFileURL(resolve('release/idraetsid-demo.html')).href);await local.locator('[data-action=login]').click();await local.locator('[data-action=existing]').click();await local.locator('[data-action=unlock]').click();await local.locator('[data-action=face]').click();await local.locator('[data-action=approve]').click();assert(await local.getByText('Du er nu',{exact:false}).isVisible());assert.equal(external,0);results.push('Selvstændig HTML åbnet via file:// i offline browser og login gennemført; ingen HTTP-requests: bestået.');
const blocked=await browser.newContext();await blocked.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new Error('blocked');}});});const bp=await blocked.newPage();await bp.goto('http://localhost:4174');await bp.locator('[data-action=login]').click();await bp.locator('[data-action=existing]').click();await bp.locator('[data-action=unlock]').click();await bp.locator('[data-action=face]').click();await bp.locator('[data-action=approve]').click();assert(await bp.getByText('Du er nu',{exact:false}).isVisible());results.push('Blokeret localStorage: flow fungerer i hukommelsen.');assert.deepEqual(failures,[]);results.push('Ingen JavaScript-runtimefejl observeret.');
await writeFile('TESTRESULTATER.md','# Automatiserede testresultater\n\n'+results.map(x=>'- '+x).join('\n')+'\n\nTestet i Playwright Chromium på Windows. Fysisk iPhone/Android-installation og enhedstastatur/safe areas kræver manuel kontrol.\n');console.log(results.join('\n'));
}finally{await browser?.close();server.close();}

