import './style.css';
const DEMO = {name:'Anders Jensen',birth:'14.03.2008',email:'anders@example.test',phone:'+45 00 00 00 00',club:'Roskilde IF',sport:'Fodbold',role:'Aktiv spiller',id:'DEMO-ID-0001'};
type Screen = 'club'|'welcome'|'verify'|'mitid'|'details'|'role'|'security'|'home'|'profile'|'settings'|'activity'|'request'|'unlock'|'pin'|'swipe'|'success'|'logged';
type Request = {id:string;unlocked:boolean;approved:boolean};
type State = {onboarded:boolean;secured:boolean;face:boolean;email:string;phone:string;request:Request|null;screen:Screen};
const KEY='idraetsid-study-v1';
const fresh=():State=>({onboarded:false,secured:false,face:false,email:DEMO.email,phone:DEMO.phone,request:null,screen:'club'});
let state=fresh();
try {const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x && typeof x.onboarded==='boolean' && typeof x.secured==='boolean' && typeof x.face==='boolean' && typeof x.email==='string' && typeof x.phone==='string')state={...fresh(),onboarded:x.onboarded,secured:x.secured,face:x.face,email:x.email,phone:x.phone};}catch{}
let error='';
const root=document.querySelector<HTMLDivElement>('#app')!;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const logo=(white=false)=>`<div class="brand ${white?'white':''}"><svg viewBox="0 0 40  sixty" aria-hidden="true"><path d="M20 0 31 17 20 29 9 17Z M8 22 18 33 10 42 0 31Z M32 22 40 31 30 42 22 33Z M20 37 27 45 20 53 13 45Z"/><circle cx="13" cy="53" r="2" fill="#2c9e54"/><circle cx="27" cy="53" r="2" fill="#2c9e54"/><circle cx="20" cy="59" r="2" fill="#e9a823"/></svg><span>IdrætsID</span></div>`.replace('40  sixty','0 0 40 62').replace('0 0 0 0','0 0');
const crest=()=>'<span class="crest" aria-hidden="true">RIF<span>▥</span></span>';
const btn=(text:string,action:string,cls='primary')=>`<button class="${cls}" data-action="${action}">${text}</button>`;
const hint=(text:string)=>`<p class="hint">${text}</p>`;
const title=(small:string,big:string,sub='')=>`<p class="eyebrow">${small}</p><h1>${big}</h1>${sub?`<p class="intro">${sub}</p>`:''}`;
function save(){try{localStorage.setItem(KEY,JSON.stringify({onboarded:state.onboarded,secured:state.secured,face:state.face,email:state.email,phone:state.phone}));}catch{}}
function go(screen:Screen,push=true){state.screen=screen;error='';save();if(push)history.pushState({screen},'',`#${screen}`);render();window.scrollTo(0,0);}
function newRequest(){state.request={id:crypto.randomUUID?.()||String(Date.now()),unlocked:false,approved:false};}
function existing(){state.onboarded=true;state.secured=true;state.face=true;}
function start(mode:'new'|'existing'|'retry'){if(mode==='new')state=fresh();if(mode==='existing')existing();newRequest();go(mode==='new'?'welcome':state.onboarded?'request':'welcome');}
function approve(){if(state.request?.unlocked&&!state.request.approved){state.request.approved=true;go('success');}}
function allowed(s:Screen):Screen{if(['home','profile','settings','activity','request','unlock','pin','swipe','success','logged'].includes(s)&&!state.onboarded)return 'welcome';if(['unlock','pin','swipe','success','logged'].includes(s)&&!state.request)return 'home';if(s==='swipe'&&!state.request?.unlocked)return 'unlock';if(['success','logged'].includes(s)&&!state.request?.approved)return 'request';return s;}
window.addEventListener('popstate',e=>{if(state.request)state.request.unlocked=false;go(allowed(e.state?.screen||'club'),false);});
function nav(){return `<nav aria-label="Primær navigation">${[['home','⌂','Hjem'],['activity','▦','Aktivitet'],['profile','♙','Profil']].map(([s,i,t])=>`<button data-action="${s}" ${state.screen===s?'aria-current="page"':''}><span>${i}</span>${t}</button>`).join('')}</nav>`;}
function body():string{switch(state.screen){
case 'club':return `<header class="club-header">${crest()}<b>Roskilde IF</b><span>Fodbold & fællesskab</span></header><div class="hero"><div class="pitch"><span class="player">10</span><span class="ball">●</span></div><div class="hero-copy"><p class="eyebrow">DIN KLUB. DIT FÆLLESSKAB.</p><h1>Fællesskab.<br>Udvikling.<br>Flere oplevelser.</h1></div></div><section>${title('VELKOMMEN I ROSKILDE IF','Én indgang til din klub','Log ind med dit IdrætsID og find dit medlemskab samlet ét sted.')}${btn('Log ind med IdrætsID','login')}${btn('Andre loginmuligheder','other','link')}<p class="club-sign">Mere end sport</p></section>`;
case 'welcome':return `<div class="welcome-top">${logo(true)}<span class="pill">Én identitet · Flere muligheder</span></div><div class="welcome-copy">${title('IDRÆT SAMLER OS','Velkommen<br>til IdrætsID','Én identitet til hele din idrætsverden. Mere tid til fællesskabet.')}</div><div class="bottom">${btn('Opret IdrætsID','verify','light')}${btn('Jeg har allerede et IdrætsID','existing','ghost')}${hint('Du afprøver en fiktiv profil. Ingen konto bliver oprettet.')}</div>`;
case 'verify':return `${title('OPRETTELSE · 1 AF 4','Verificer med MitID','Et trygt første skridt til dit IdrætsID.')}<div class="mitid-art">Mit<span>●</span>ID</div><div class="notice">I denne demo er identitetskontrollen simuleret. Du skal ikke bruge dit rigtige MitID.</div><div class="bottom">${btn('Fortsæt med MitID →','mitid')}${btn('Tilbage','welcome','link')}</div>`;
case 'mitid':return `${title('SIMULERET MITID','Godkend din demoidentitet','Vi bruger den fiktive person Anders Jensen.')}<div class="identity"><span class="round-icon">✓</span><b>Anders Jensen</b><p>Født ${DEMO.birth}</p></div>${hint('Ingen MitID-forbindelse. Ingen personlige loginoplysninger.')}${btn('Simulér godkendelse','details')}${btn('Annuller verificering','verify','link')}`;
case 'details':return `${title('OPRETTELSE · 2 AF 4','Dine oplysninger','Tjek de forudfyldte demodata, og prøv eventuelt at ændre kontaktoplysningerne.')}<form id="details"><label>Navn<input value="${DEMO.name}" readonly></label><label>Fødselsdato<input value="${DEMO.birth}" readonly></label><div class="field-note">Låste demo-identitetsoplysninger</div><label>E-mail<input name="email" type="email" value="${esc(state.email)}" required autocomplete="off"></label><label>Telefonnummer<input name="phone" type="tel" value="${esc(state.phone)}" required autocomplete="off" aria-describedby="phone-help"></label><p id="phone-help" class="field-note">Demoværdi: +45 00 00 00 00. Brug kun fiktive oplysninger.</p><label class="check"><input type="checkbox">Jeg vil gerne modtage information om IdrætsID (valgfrit)</label><p role="alert" class="error">${error}</p><button class="primary" type="submit">Fortsæt</button></form>`;
case 'role':return `${title('OPRETTELSE · 3 AF 4','Hvilken rolle har du i idrætten?','Dit IdrætsID tager udgangspunkt i dig.')}<div class="role selected"><span>♙</span><div><b>Jeg er spiller / Idrætsudøver</b><small>Den valgte rolle i denne demo</small></div><b>✓</b></div>${['Jeg er træner','Jeg er forælder','Jeg er frivillig','Andet'].map(t=>`<div class="role disabled"><span>♙</span><div>${t}<small>Ikke med i denne prototype</small></div></div>`).join('')}<div class="bottom">${btn('Fortsæt','security')}</div>`;
case 'security':return `${title('OPRETTELSE · 4 AF 4','Opret sikker adgang','Vælg en demo-PIN, og afprøv eventuelt simuleret Face ID.')}<form id="security"><label>Demo-PIN<input name="pin" type="password" inputmode="numeric" maxlength="4" autocomplete="off" required placeholder="••••"></label><div class="notice">Brug demokoden <b>1234</b> — ikke din rigtige pinkode</div><label class="check option"><input name="face" type="checkbox"><span><b>Aktivér simuleret Face ID</b><small>Valgfrit · Ingen kameraadgang eller tilladelser</small></span></label><p class="error" role="alert">${error}</p><button class="primary">Opret mit demo-IdrætsID</button></form>`;
case 'home':return `${title('DIT IDRÆTSID','Hej Anders','Velkommen til dit idrætsfællesskab.')}<button class="id-card" data-action="profile"><div><b>${DEMO.name}</b><small>Født ${DEMO.birth}<br>Idrætsudøver</small><span>✓ Verificeret · Simulation</span></div><b>›</b></button><div class="section-label"><h2>Mine foreninger</h2><span>Demomedlemskab</span></div><div class="membership">${crest()}<div><b>Roskilde IF</b><small>Fodbold · Aktiv spiller</small></div><span class="status-dot"></span></div>${state.request&&!state.request.approved?`<div class="pending"><p class="eyebrow">LOGIN VENTER</p><h2>Din klub er klar</h2><p>Fortsæt det login, du startede hos Roskilde IF.</p>${btn('Fortsæt login til Roskilde IF','request')}</div>`:btn('Gå til klubplatformen','club','secondary')}<div class="rows">${btn('♙ Mine oplysninger <span>›</span>','profile','row')}${btn('⚙ Indstillinger <span>›</span>','settings','row')}</div>${nav()}`;
case 'profile':return `${title('PROFIL','Mine oplysninger','Din fiktive profil i IdrætsID.')}<dl><dt>Navn</dt><dd>${DEMO.name}</dd><dt>Fødselsdato</dt><dd>${DEMO.birth}</dd><dt>E-mail</dt><dd>${esc(state.email)}</dd><dt>Telefon</dt><dd>${esc(state.phone)}</dd><dt>IdrætsID</dt><dd>${DEMO.id}</dd><dt>Rolle</dt><dd>Idrætsudøver / aktiv spiller</dd></dl>${hint('Klubtilknytningen og verificeringen er seeded demodata.')}${btn('Indstillinger','settings','secondary')}${nav()}`;
case 'settings':return `${title('INDSTILLINGER','Din demosikkerhed')}<div class="notice"><b>Demo-PIN er opsat</b><p>Koden er altid 1234. Indtastede pinkoder gemmes aldrig.</p></div><label class="check option"><input id="face-setting" type="checkbox" ${state.face?'checked':''}><span>Simuleret Face ID<small>Kan slås til og fra uden enhedstilladelser.</small></span></label>${btn('Nulstil demo','reset','secondary')}${nav()}`;
case 'activity':return `${title('AKTIVITET','Det sker i din klub','Træning, kampe og klubaktiviteter administreres på Roskilde IF’s platform.')}<div class="membership">${crest()}<div><b>Roskilde IF</b><small>Dit fodboldfællesskab</small></div></div>${hint('Denne prototype viser loginrejsen. Aktiviteter er ikke en del af demoen.')}${btn('Åbn klubplatformen','club')}${nav()}`;
case 'request':return `<div class="request-brand">${crest()}<b>Roskilde IF</b></div>${title('KLUBPLATFORMEN','Anmoder om login','Roskilde IF vil give dig adgang til sin platform via IdrætsID.')}<div class="notice"><small>DU LOGGER IND SOM</small><p><b>${DEMO.name}</b><br>${esc(state.email)}</p><hr><p>Adgang til din profil og dit demomedlemskab.</p></div>${hint('Fiktiv loginanmodning · Ingen oplysninger sendes til klubben.')}<div class="bottom">${btn('Fortsæt i IdrætsID','unlock')}${btn('Annuller','cancel','link')}</div>`;
case 'unlock':return `${title('SIMULERET SIKKERHED','Lås dit IdrætsID op','Lås først op. Derefter vælger du selv, om klubbens login skal godkendes.')}<div class="face-art" aria-hidden="true">⌗</div>${state.face?`${btn('Simulér Face ID','face')}${btn('Brug demo-PIN i stedet','pin','secondary')}${btn('Simulér mislykket Face ID','face-error','link')}`:`${hint('Face ID blev sprunget over. Brug din demo-PIN.')}${btn('Brug demo-PIN','pin')}`}<p class="error" role="alert">${error}</p>${btn('Annuller login','cancel','link')}`;
case 'pin':return `${title('SIMULERET SIKKERHED','Indtast demo-PIN','Lås op for loginanmodningen fra Roskilde IF.')}<form id="pin"><label>Demo-PIN<input name="pin" type="password" inputmode="numeric" maxlength="4" autocomplete="off" placeholder="••••" required autofocus></label><div class="notice">Brug demokoden <b>1234</b> — ikke din rigtige pinkode</div><p role="alert" class="error">${error}</p><button class="primary">Lås op</button></form>${btn('Tilbage','unlock','link')}${btn('Annuller login','cancel','link')}`;
case 'swipe':return `<div class="swipe-brand">${logo(true)}</div>${title('DU HAR LÅST OP','Log ind med IdrætsID','Roskilde IF vil logge dig ind')}<div class="destination"><span>KLUBPLATFORM</span><b>Roskilde IF</b><small>${DEMO.name}</small></div><div class="bottom"><div id="swipe" class="swipe-track"><span class="swipe-label">Swipe for at logge ind</span><button id="handle" aria-label="Træk for at godkende login">→</button></div>${hint('Træk pilen helt til højre for at godkende.')}${btn('Godkend login med knap','approve','ghost')}${btn('Annuller','cancel','ghost')}${hint('Simuleret godkendelse · Ingen rigtigt login')}</div>`;
case 'success':return `<div class="success-icon">✓</div>${title('LOGIN GODKENDT','Du er nu<br>logget ind','Du har fået adgang til Roskilde IF’s simulerede platform.')}<div class="notice"><b>${DEMO.name}</b><p>IdrætsID · ${DEMO.id}</p></div><div class="bottom">${btn('Gå til foreningens side','logged')}${hint('Demoen bliver i dette vindue.')}</div>`;
case 'logged':return `<header class="club-header">${crest()}<b>Roskilde IF</b></header>${title('MIN KLUB','Velkommen, Anders','Du er logget ind på den simulerede klubplatform.')}<div class="membership">${crest()}<div><b>Dit medlemskab</b><small>Fodbold · Aktiv spiller</small></div></div><div class="notice"><b>En del af fællesskabet</b><p>Her ville du finde din forenings eksisterende funktioner. Denne demo viser din adgang og medlemsoversigt.</p></div>${btn('Se mit IdrætsID','home','secondary')}${btn('Log ud','logout')}`;
}}

const SCREENS: {screen:Screen; step:string; label:string; group:string; tone:string}[] = [
  {screen:'club',step:'1',label:'Klubplatform',group:'Oprettelse',tone:'blue'},
  {screen:'welcome',step:'2',label:'Velkommen',group:'Oprettelse',tone:'burgundy'},
  {screen:'verify',step:'3',label:'Verificer med MitID',group:'Oprettelse',tone:'white'},
  {screen:'mitid',step:'3A',label:'MitID-simulation',group:'Oprettelse',tone:'white'},
  {screen:'details',step:'4',label:'Dine oplysninger',group:'Oprettelse',tone:'white'},
  {screen:'role',step:'5',label:'Vælg rolle',group:'Profil & tilknytning',tone:'white'},
  {screen:'security',step:'6',label:'Sikker adgang',group:'Profil & tilknytning',tone:'white'},
  {screen:'home',step:'7',label:'Forside & medlemskab',group:'Profil & tilknytning',tone:'white'},
  {screen:'profile',step:'7A',label:'Profil',group:'Profil & tilknytning',tone:'white'},
  {screen:'settings',step:'7B',label:'Indstillinger',group:'Profil & tilknytning',tone:'white'},
  {screen:'activity',step:'7C',label:'Aktivitet',group:'Profil & tilknytning',tone:'white'},
  {screen:'request',step:'8',label:'Loginanmodning',group:'Godkendelse af login',tone:'blue'},
  {screen:'unlock',step:'9A',label:'Lås op · Face ID',group:'Godkendelse af login',tone:'white'},
  {screen:'pin',step:'9A',label:'Lås op · PIN',group:'Godkendelse af login',tone:'white'},
  {screen:'swipe',step:'9B',label:'Swipe & godkend',group:'Godkendelse af login',tone:'burgundy'},
  {screen:'success',step:'10',label:'Login godkendt',group:'Godkendelse af login',tone:'green'},
  {screen:'logged',step:'10A',label:'Indlogget klubside',group:'Godkendelse af login',tone:'blue'},
];
function previewScreen(screen:Screen){
  const early=['club','welcome','verify','mitid','details','role','security'].includes(screen);
  state.onboarded=!early;state.secured=!early;
  if(screen==='club')state.request=null;
  else {newRequest();state.request!.unlocked=['swipe','success','logged'].includes(screen);state.request!.approved=['success','logged'].includes(screen);}
  if(screen==='unlock')state.face=true;
  go(screen);
}

function appMarkup(){const red=['welcome','swipe'].includes(state.screen);const club=['club','request','logged'].includes(state.screen);return `<div class="app-shell ${red?'red':''} ${club?'club-theme':''}"><div class="utility"><span>Studieprototype · Fiktive data</span><details><summary>Demo</summary><div class="demo-menu">${btn('Start som ny bruger','new','row')}${btn('Start som eksisterende bruger','demo-existing','row')}${btn('Prøv login igen','retry','row')}${btn('Nulstil demo','reset','row')}</div></details></div><main id="main" tabindex="-1">${!red&&!club?`<header class="app-header">${logo()}${!['verify'].includes(state.screen)?btn('‹','back','back'):''}</header>`:''}${body()}</main><div id="install-help"></div><div class="footer-mark">Idræt samler os</div></div>`;}
function screenDocument(screen:Screen){
  const original=state, originalError=error;
  state={...state,screen,face:screen==='unlock'?true:state.face,request:{id:'preview',unlocked:['swipe','success','logged'].includes(screen),approved:['success','logged'].includes(screen)}};error='';
  let markup='';try{markup=appMarkup();}finally{state=original;error=originalError;}
  const css=Array.from(document.styleSheets).map(sheet=>{try{return Array.from(sheet.cssRules).map(rule=>rule.cssText).join('\n');}catch{return '';}}).join('\n');
  return '<!doctype html><html lang="da"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+css+'\nhtml,body{margin:0;background:white;overflow:hidden}.app-shell{width:390px;min-height:844px;border:0;border-radius:0;box-shadow:none}</style></head><body>'+markup+'</body></html>';
}

function overview(){return `<section class="screen-overview" aria-labelledby="overview-title"><div class="overview-heading"><div><p class="eyebrow">BRUGERREJSEN</p><h2 id="overview-title">Vælg en skærm</h2></div><p>Scroll vandret for overblik · Klik for at åbne en demo af trinnet</p></div><div class="screen-strip" aria-label="Alle prototypeskærme">${SCREENS.map(x=>`<article class="screen-card"><div class="screen-preview" inert aria-hidden="true"><iframe tabindex="-1" title="Miniature: ${x.label}" sandbox="allow-same-origin" srcdoc="${esc(screenDocument(x.screen))}"></iframe></div><button class="screen-choice" data-screen="${x.screen}" aria-pressed="${state.screen===x.screen}" aria-controls="main"><span class="screen-label"><b>${x.step}</b><span>${x.label}</span></span><small>${x.group}</small></button></article>`).join('')}</div></section>`;}
function bindOverview(){
  root.querySelectorAll<HTMLIFrameElement>('.screen-preview iframe').forEach(frame=>{frame.onload=()=>{const height=Math.max(844,frame.contentDocument?.querySelector('.app-shell')?.scrollHeight||844);const scale=Math.min(128/390,264/height);frame.style.height=height+'px';frame.style.transform='scale('+scale+')';frame.style.left=(128-390*scale)/2+'px';};});
  root.querySelectorAll<HTMLButtonElement>('[data-screen]').forEach(b=>b.onclick=()=>previewScreen(b.dataset.screen as Screen));
  const strip=root.querySelector<HTMLDivElement>('.screen-strip')!;
  const active=strip.querySelector<HTMLButtonElement>('[aria-pressed="true"]')!;
  strip.scrollLeft=Math.max(0,active.parentElement!.offsetLeft-strip.clientWidth/2+active.parentElement!.offsetWidth/2);
  strip.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const choices=Array.from(strip.querySelectorAll<HTMLButtonElement>('button'));const index=choices.indexOf(document.activeElement as HTMLButtonElement);if(index<0)return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?choices.length-1:Math.max(0,Math.min(choices.length-1,index+(e.key==='ArrowRight'?1:-1)));choices[next].focus();};
}

function render(){const red=['welcome','swipe'].includes(state.screen);const club=['club','request','logged'].includes(state.screen);root.innerHTML=`<aside class="desktop-note"><p class="eyebrow">IDRÆTSID · INTERAKTIV DEMO</p><h2>Én identitet.<br>Et stærkere<br>fællesskab.</h2><p>Fra første besøg til godkendt login.<br>Prøv rejsen i dit eget tempo.</p><div class="journey"><span class="${['welcome','verify','mitid','details'].includes(state.screen)?'active':''}">01 Oprettelse</span><span class="${['role','security','home'].includes(state.screen)?'active':''}">02 Profil & tilknytning</span><span class="${['request','unlock','pin','swipe','success','logged'].includes(state.screen)?'active':''}">03 Godkendelse af login</span></div><p class="note-small">Alle oplysninger og sikkerhedstrin er fiktive.</p></aside>${appMarkup()}`;root.insertAdjacentHTML('beforeend',overview());bindOverview();root.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action!));bindForms();bindSwipe();installHelp();document.querySelector<HTMLElement>('#main')?.focus({preventScroll:true});}
function action(a:string){switch(a){case 'login':newRequest();go(state.onboarded?'request':'welcome');break;case 'existing':existing();if(!state.request)newRequest();go('request');break;case 'new':start('new');break;case 'demo-existing':start('existing');break;case 'retry':start('retry');break;case 'reset':state=fresh();try{localStorage.removeItem(KEY);}catch{}go('club');break;case 'face':if(state.request){state.request.unlocked=true;go('swipe');}break;case 'face-error':error='Face ID-simulationen lykkedes ikke. Prøv igen eller vælg PIN.';render();break;case 'approve':approve();break;case 'cancel':state.request=null;go('club');break;case 'logout':state.request=null;go('club');break;case 'other':error='Andre loginmetoder er ikke med i denne prototype.';alert(error);break;case 'back':{const prev:Partial<Record<Screen,Screen>>={details:'verify',role:'details',security:'role',mitid:'verify',profile:'home',settings:'home',activity:'home',request:'home',unlock:'request',pin:'unlock',swipe:'unlock',success:'home',logged:'home',home:'club'};if(state.request)state.request.unlocked=false;go(prev[state.screen]||'club');break;}default:go(allowed(a as Screen));}}
function bindForms(){const form=root.querySelector<HTMLFormElement>('form');if(form)form.onsubmit=e=>{e.preventDefault();const data=new FormData(form);if(form.id==='details'){const email=String(data.get('email')).trim(),phone=String(data.get('phone')).trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!/^\+?[\d\s()-]{8,20}$/.test(phone)){error='Angiv en gyldig demo-e-mail og et telefonnummer med mindst 8 tegn.';render();return;}state.email=email;state.phone=phone;go('role');}else if(String(data.get('pin'))!=='1234'){error='Forkert demokode. Prøv igen med 1234.';render();}else if(form.id==='security'){state.secured=true;state.onboarded=true;state.face=data.has('face');go('home');}else if(state.request){state.request.unlocked=true;go('swipe');}};const setting=root.querySelector<HTMLInputElement>('#face-setting');if(setting)setting.onchange=()=>{state.face=setting.checked;save();};}
function bindSwipe(){const handle=root.querySelector<HTMLButtonElement>('#handle'),track=root.querySelector<HTMLDivElement>('#swipe');if(!handle||!track)return;let start=0,pos=0,drag=false;const max=()=>track.clientWidth-handle.offsetWidth-12;const reset=()=>{drag=false;pos=0;handle.style.transform='';track.style.setProperty('--progress','0px');track.classList.remove('dragging');};handle.onpointerdown=e=>{if(!state.request?.unlocked)return;drag=true;start=e.clientX;handle.setPointerCapture(e.pointerId);track.classList.add('dragging');};handle.onpointermove=e=>{if(!drag)return;pos=Math.max(0,Math.min(max(),e.clientX-start));handle.style.transform=`translateX(${pos}px)`;track.style.setProperty('--progress',`${pos+52}px`);};handle.onpointerup=()=>{if(drag&&pos>=max()*.92){drag=false;approve();}else reset();};handle.onpointercancel=reset;handle.onlostpointercapture=()=>{if(drag)reset();};handle.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();approve();}};}
type InstallEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<unknown>};let installEvent:InstallEvent|null=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e as InstallEvent;installHelp();});window.addEventListener('appinstalled',()=>{installEvent=null;installHelp();});function installHelp(){const target=document.querySelector('#install-help');if(!target)return;const standalone=matchMedia('(display-mode: standalone)').matches||(navigator as Navigator&{standalone?:boolean}).standalone;if(standalone||location.protocol==='file:'){target.innerHTML='';return;}if(installEvent){target.innerHTML='<button class="link" id="install">Føj til hjemmeskærm</button>';target.querySelector<HTMLButtonElement>('button')!.onclick=async()=>{await installEvent?.prompt();await installEvent?.userChoice;installEvent=null;installHelp();};}else target.innerHTML=`<details class="install"><summary>Føj til hjemmeskærm · Hjælp</summary><p>På iPhone: Åbn HTTPS-udgaven i Safari → Del → Føj til hjemmeskærm → Åbn som webapp, når muligheden vises. Andre browsere viser installation, når det understøttes.</p></details>`;}
if(location.protocol!=='file:'&&window.isSecureContext&&'serviceWorker'in navigator)window.addEventListener('load',()=>{navigator.serviceWorker.register('./sw.js').catch(()=>{});});
history.replaceState({screen:'club'},'','#club');render();
